//INIT  EXEC PGM=DFHCSDUP
//STEPLIB DD DSN=CICS.TS54.SDFHLOAD,DISP=SHR
//DFHCSD  DD DSN=CICS.DFHCSD.XPROV.TCICS42,DISP=SHR
//SYSPRINT DD SYSOUT=V
//*Reihenfolge ist WICHTIG!!
//SYSIN   DD *
ADD LIST(TCICS42) GROUP(TESTPCT)
ADD LIST(TCICS42) GROUP(DB0C)
ADD LIST(TCICS42) GROUP(RCTTEST)
ADD LIST(TCICS42) GROUP(FCTT1)
ADD LIST(TCICS42) GROUP(MQPROV01)
//
